# Generated by Django 5.2.6 on 2025-09-30 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('civil', 'Civil Law'), ('criminal', 'Criminal Law'), ('family', 'Family Law'), ('property', 'Property / Real Estate Law'), ('corporate', 'Corporate Law'), ('business', 'Commercial / Business Law'), ('contract', 'Contract Law'), ('banking', 'Banking & Finance Law'), ('competition', 'Competition Law'), ('insolvency', 'Insolvency / Bankruptcy Law'), ('administrative', 'Administrative Law'), ('constitutional', 'Constitutional Law'), ('human_rights', 'Human Rights / Public Interest Law'), ('environmental', 'Environmental Law'), ('international', 'International Law / Trade Law'), ('immigration', 'Immigration Law'), ('intellectual_property', 'Intellectual Property Rights (IPR)'), ('cyber', 'Cyber Law / Data Privacy'), ('technology', 'Technology / IT Law'), ('fintech', 'Fintech, Blockchain & Emerging Tech'), ('media_entertainment', 'Media & Entertainment Law'), ('labour_employment', 'Labour & Employment Law'), ('tax', 'Taxation Law'), ('consumer_protection', 'Consumer Protection Law'), ('insurance', 'Insurance Law'), ('maritime', 'Maritime / Admiralty Law'), ('personal_injury', 'Personal Injury / Tort Law'), ('space_air', 'Space & Air Law'), ('defense_military', 'Military / Armed Forces / Defence Law'), ('other', 'Other')], default='other', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('won_cases', models.PositiveBigIntegerField(default=0)),
                ('service_cities', models.ManyToManyField(related_name='lawyers', to='lawyer.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
