# Generated by Django 5.2.6 on 2025-09-29 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('landmark', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('govt_id', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('crime_description', models.TextField()),
                ('incident_datetime', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaint_photos/')),
                ('file_of_complaint', models.FileField(blank=True, null=True, upload_to='complaint_files/')),
                ('witness_name', models.CharField(blank=True, max_length=100, null=True)),
                ('witness_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('privacy_option', models.CharField(choices=[('LAWYERS_ONLY', 'Visible to Lawyers Only'), ('PUBLIC_WITH_IDENTITY', 'Show Public with Identity'), ('PUBLIC_ANONYMOUS', 'Show Public without Identity')], default='LAWYERS_ONLY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('incident_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='complaints.incidentlocation')),
                ('residential_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.residential')),
            ],
        ),
    ]
